name: Sync Docs to Confluence

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**' ]
  workflow_dispatch:
    inputs:
      files-to-sync:
        description: 'Space-separated list of files to synchronize'
        required: true
        type: string

jobs:
  confluence-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get modified files from user input
        if: github.event_name == 'workflow_dispatch'
        run: echo "MODIFIED_FILES=${{ github.event.inputs.files-to-sync }}" >> $GITHUB_ENV

      - name: Get modified files from git diff
        if: github.event_name != 'workflow_dispatch'
        run: echo "MODIFIED_FILES=$(git diff HEAD^ --name-only | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Wiki Sync
        uses: talkiq/confluence-wiki-sync@v1
        with:
          wiki-base-url: https://mastella.atlassian.net/wiki
          user: ${{ secrets.CONFLUENCE_USER }}
          token: ${{ secrets.CONFLUENCE_TOKEN }}
          modified-files: ${{ env.MODIFIED_FILES }}
          space-name: TAL
          root-page-title: AcquiGen Technical Documentation
